version: "3.8"
services:
  example-db:
    container_name: example-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: false
    tty: false
    environment:
      MYSQL_ROOT_PASSWORD: ${EXAMPLE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${EXAMPLE_DB_DATABASE}
      MYSQL_USER: ${EXAMPLE_DB_USER}
      MYSQL_PASSWORD: ${EXAMPLE_DB_PASSWORD}
      MYSQL_TCP_PORT: ${EXAMPLE_DB_TCP_PORT}                  
    ports:
       - ${EXAMPLE_DB_TCP_PORT}:${EXAMPLE_DB_TCP_PORT}
    volumes:
      - type: bind      
        source: ${EXAMPLE_DB_DATAFILES_DIR}
        target: /var/lib/mysql
        read_only: false      
      - type: bind
        source: ${EXAMPLE_DB_INIT}
        target: /docker-entrypoint-initdb.d/initdb.sql
        read_only: true
    healthcheck:
        test: "mysql $${MYSQL_DATABASE} -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --port=$${MYSQL_TCP_PORT} -e 'SELECT 1;'"
        timeout: 20s
        retries: 10
